INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_CHERCHEUR');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMINMET');
INSERT IGNORE INTO types(name) VALUES('BLE');
INSERT IGNORE INTO types(name) VALUES('ORGE');